title: Awesome Factorio
description: How to build an awesome factory?

lang: en
languages: ['en', 'de']

plugins:
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
