title: Awesome Factorio
description: how to build an awesome factory

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

lang: en 
languages: ["en", "ru"] 

mermaid:
  version: "9.1.3"
